Update action.yml

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -1,40 +1,40 @@
 name: 'Dokploy Deployment'
-description: 'Triggers a deployment in Dokploy via its API'
+description: 'Triggers a deployment in Dokploy via its API.'
 
 inputs:
   auth_token:
-    description: 'Dokploy API Key for authentication'
+    description: 'Dokploy API Key for authentication.'
     required: true
   application_id:
-    description: 'The unique ID of the Dokploy application to deploy'
+    description: 'The unique ID of the Dokploy application to deploy.'
     required: true
   dokploy_url:
-    descriptionn: 'The base URL of your Dokploy instance (e.g., https://dokploy.example.com).'
+    description: 'The base URL of your Dokploy instance (e.g., https://dokploy.example.com).'
     required: true
 
 runs:
   using: 'composite'
   steps:
     - name: Trigger Dokploy Deployment
+      env:
+        DOKPLOY_URL: ${{ inputs.dokploy_url }}
+        DOKPLOY_API_KEY: ${{ inputs.auth_token }}
+        DOKPLOY_APPLICATION_ID: ${{ inputs.application_id }}
+      shell: bash
       run: |
-        curl -X 'POST' \
-        "$DOKPLOY_URL/api/application.deploy" \
-        -H 'accept: application/json' \
-        -H 'Content-Type: application/json' \
-        -H "x-api-key: $DOKPLOY_API_KEY" \
-        -d "{\"applicationId\": \"$DOKPLOY_APPLICATION_ID\"}" \
-        -w "%{http_code}" \
-        -o /dev/null \
-        -s)
-
-      if [ "$response" -ne 200 ]; then
-        echo "Deployment failed with status code: $response"
-        exit 1
-      else
-        echo "Deployment successful!"
-      fi
-    shell: bash
-    env:
-      DOKPLOY_URL: ${{ inputs.dokploy_url }}
-      DOKPLOY_API_KEY: ${{ inputs.auth_token }}
-      DOKPLOY_APPLICATION_ID: ${{ inputs.application_id }}
+        response=$(curl -X 'POST' \
+          "$DOKPLOY_URL/api/application.deploy" \
+          -H 'accept: application/json' \
+          -H 'Content-Type: application/json' \
+          -H "x-api-key: $DOKPLOY_API_KEY" \
+          -d "{\"applicationId\": \"$DOKPLOY_APPLICATION_ID\"}" \
+          -w "%{http_code}" \
+          -o /dev/null \
+          -s)
+        
+        if [ "$response" -ne 200 ]; then
+          echo "Deployment failed with status code: $response"
+          exit 1
+        else
+          echo "Deployment successful!"
+        fi
